name: Build and Test FastAPI Backend

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'app/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8
          pip install -r app/requirements.txt

      - name: Lint with flake8
        run: flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Test with pytest
        working-directory: ./app
        run: pytest || echo "No tests configured"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API Docker image (local)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: saburo-api:local-test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Save commit info
        if: github.event_name != 'pull_request'
        run: |
          mkdir -p /tmp/artifacts
          echo "${{ github.sha }}" > /tmp/artifacts/commit-sha

      - name: Upload commit SHA
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: backend-commit-info
          path: /tmp/artifacts/commit-sha
          retention-days: 7